TeamplateHotel/Areas/Administrator/Controllers/PlugInController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ProjectLibrary.Database;

namespace TeamplateHotel.Areas.Administrator.Controllers
{
    public class PlugInController : BaseController
    {
        [HttpGet]
        public ActionResult CSS()
        {
            ViewBag.Title = "Chỉnh sửa CSS";
            using (var db = new MyDbDataContext())
            {
                Plugin plugin = db.Plugins.FirstOrDefault();
                return View(plugin);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CSS(Plugin model)
        {
            using (var db = new MyDbDataContext())
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        Plugin plugin = db.Plugins.FirstOrDefault();
                        plugin.CSS = model.CSS;
                        db.SubmitChanges();
                        ViewBag.Messages = "Chỉnh sửa CSS thành công";
                        return RedirectToAction("CSS");
                    }
                    catch (Exception exception)
                    {
                        ViewBag.Messages = "Lỗi: " + exception.Message;
                        return View();
                    }
                }
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult GoogleAnalytics()
        {
            ViewBag.Title = "Thêm Google analytics, Live chat";
            using (var db = new MyDbDataContext())
            {
                Plugin plugin = db.Plugins.FirstOrDefault();
                return View(plugin);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult GoogleAnalytics(Plugin model)
        {
            using (var db = new MyDbDataContext())
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        Plugin plugin = db.Plugins.FirstOrDefault();
                        plugin.JS = model.JS;
                        db.SubmitChanges();
                        ViewBag.Messages = "Chỉnh sửa Google Analytics & Live chat thành công";
                        return RedirectToAction("GoogleAnalytics");
                    }
                    catch (Exception exception)
                    {
                        ViewBag.Messages = "Lỗi: " + exception.Message;
                        return View();
                    }
                }
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult SideBar()
        {
            ViewBag.Title = "Thêm sideBar";
            using (var db = new MyDbDataContext())
            {
                Plugin plugin = db.Plugins.FirstOrDefault();
                return View(plugin);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SideBar(Plugin model)
        {
            using (var db = new MyDbDataContext())
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        Plugin plugin = db.Plugins.FirstOrDefault();
                        plugin.SideBar = model.SideBar;
                        db.SubmitChanges();
                        ViewBag.Messages = "Chỉnh sửa SideBar thành công";
                        return RedirectToAction("SideBar");
                    }
                    catch (Exception exception)
                    {
                        ViewBag.Messages = "Lỗi: " + exception.Message;
                        return View();
                    }
                }
                return View(model);
            }
        }
    }
}

TeamplateHotel/Areas/Administrator/Views/PlugIn/CSS.cshtml
@model ProjectLibrary.Database.Plugin
@{
    Layout = "~/Areas/Administrator/Views/Templates/_LayoutPage.cshtml";
}
<div class="span12">
    <div class="widget ">
        <div class="widget-header">
            <i class=" icon-plus-sign"></i>
            <h3>@ViewBag.Title</h3>
        </div> <!-- /widget-header -->

        <div class="widget-content">
            @Html.ValidationSummary(true)
            @using (Html.BeginForm("CSS", "PlugIn", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="control-group">
                    <label class="control-label" for="Content">Mã CSS</label>
                    <div class="controls">
                        @Html.TextAreaFor(c => c.CSS, new { @class = "textarea-big" })
                    </div>
                </div>

                <div class="form-actions">
                    <input type="submit" value="Submit" class="btn btn-primary" />
                    <a href="@Url.Action("Index", "ControlPanel")" class="btn">Cancel</a>
                </div>
            }
        </div>
    </div>
</div>

TeamplateHotel/Areas/Administrator/Views/PlugIn/GoogleAnalytics.cshtml
@model ProjectLibrary.Database.Plugin
@{
    Layout = "~/Areas/Administrator/Views/Templates/_LayoutPage.cshtml";
}
<div class="span12">
    <div class="widget ">
        <div class="widget-header">
            <i class=" icon-plus-sign"></i>
            <h3>@ViewBag.Title</h3>
        </div> <!-- /widget-header -->

        <div class="widget-content">
            @Html.ValidationSummary(true)
            @using (Html.BeginForm("GoogleAnalytics", "PlugIn", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="control-group">
                    <label class="control-label" for="Content">Mã Google Analytics, Live chat, facebook... </label>
                    <div class="controls">
                        @Html.TextAreaFor(c => c.JS, new { @class = "textarea-big" })
                    </div>
                </div>

                <div class="form-actions">
                    <input type="submit" value="Submit" class="btn btn-primary" />
                    <a href="@Url.Action("Index", "ControlPanel")" class="btn">Cancel</a>
                </div>
            }
        </div>
    </div>
</div>

TeamplateHotel/Areas/Administrator/Views/PlugIn/SideBar.cshtml
@model ProjectLibrary.Database.Plugin
@{
    Layout = "~/Areas/Administrator/Views/Templates/_LayoutPage.cshtml";
}
<div class="span12">
    <div class="widget ">
        <div class="widget-header">
            <i class=" icon-plus-sign"></i>
            <h3>@ViewBag.Title</h3>
        </div> <!-- /widget-header -->

        <div class="widget-content">
            @Html.ValidationSummary(true)
            @using (Html.BeginForm("SideBar", "PlugIn", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="control-group">
                    <label class="control-label" for="Content">Mã HTML cho sidebar </label>
                    <div class="controls">
                        @Html.TextAreaFor(c => c.SideBar, new { @class = "textarea-big" })
                    </div>
                </div>

                <div class="form-actions">
                    <input type="submit" value="Submit" class="btn btn-primary" />
                    <a href="@Url.Action("Index", "ControlPanel")" class="btn">Cancel</a>
                </div>
            }
        </div>
    </div>
</div>